# Generated by Django 5.1.6 on 2025-02-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_priestprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="priestprofile",
            name="experience",
            field=models.IntegerField(),
        ),
    ]
